In [19]:
#BASE DE DATOS DE JUGADORES DE FUTBOL Y SUS GOLES POR 10 TEMPORADAS
import random


# Lista de nombres
nombres = ["Lewa", "Messi", "Ronaldo", "Neymar", "Suarez", "Aguero", "Ibra", "Haaland", "Mbappe", "Julio Cesar"]

# Generar matriz de datos aleatorios
matriz_datos = []
for _ in range(10):
    filas= [random.randint(15, 50) for _ in range(10)]  # 10 datos aleatorios por fila
    matriz_datos.append(filas)

In [21]:
import pandas as pd
# Crear un DataFrame utilizando pandas
matriz = pd.DataFrame(matriz_datos, columns=[f"Temporada{i+1}" for i in range(10)], index=nombres)

# Mostrar la tabla
matriz

,Temporada1,Temporada2,Temporada3,Temporada4,Temporada5,Temporada6,Temporada7,Temporada8,Temporada9,Temporada10
Lewa,35,29,35,35,49,15,20,36,29,32
Messi,47,17,29,40,46,42,25,23,27,50
Ronaldo,41,37,22,47,36,16,16,33,20,24
Neymar,39,47,49,47,36,49,16,36,25,17
Suarez,20,42,47,32,30,44,28,22,32,38
Aguero,27,31,41,19,45,47,37,22,19,19
Ibra,30,27,50,31,36,28,37,50,38,44
Haaland,32,15,30,30,29,47,48,37,47,45
Mbappe,19,29,24,15,33,46,41,16,47,17
El Profe,17,27,18,40,34,18,38,23,32,28