In [35]:
import pandas as pd
etf=pd.read_csv("ETF prices.csv")
etf

        fund_symbol  price_date   open   high    low  close  adj_close  volume
0               AAA  2020-09-09  25.10  25.12  25.07  25.07      24.85   17300
1               AAA  2020-09-10  25.06  25.07  25.05  25.07      24.85   23500
2               AAA  2020-09-11  25.04  25.05  25.02  25.03      24.81   33400
3               AAA  2020-09-14  25.01  25.06  25.01  25.02      24.80   13100
4               AAA  2020-09-15  25.02  25.03  25.01  25.01      24.79   12100
...             ...         ...    ...    ...    ...    ...        ...     ...
3866025         ZSL  2021-11-23  26.81  27.21  26.30  26.35      26.35  190900
3866026         ZSL  2021-11-24  26.79  26.96  26.57  26.69      26.69  109000
3866027         ZSL  2021-11-26  26.67  28.14  26.67  27.72      27.72  205500
3866028         ZSL  2021-11-29  27.89  28.56  27.80  28.27      28.27  411900
3866029         ZSL  2021-11-30  28.15  28.73  25.91  28.49      28.49  219400

[3866030 rows x 8 columns]

In [38]:
d.shape

(1476592, 8)

In [33]:
d.ndim

2

In [34]:
d.drop(columns=["low", "high"])

        fund_symbol  price_date   open  close  adj_close   volume
0               AAA  2020-09-09  25.10  25.07      24.85  17300.0
1               AAA  2020-09-10  25.06  25.07      24.85  23500.0
2               AAA  2020-09-11  25.04  25.03      24.81  33400.0
3               AAA  2020-09-14  25.01  25.02      24.80  13100.0
4               AAA  2020-09-15  25.02  25.01      24.79  12100.0
...             ...         ...    ...    ...        ...      ...
1476587        GURU  2018-04-18  30.82  30.86      29.69   4700.0
1476588        GURU  2018-04-19  30.77  30.58      29.42   6900.0
1476589        GURU  2018-04-20  30.49  30.41      29.26   2200.0
1476590        GURU  2018-04-23  30.45  30.31      29.16   3800.0
1476591        GURU         201    NaN    NaN        NaN      NaN

[1476592 rows x 6 columns]

In [31]:
d["open"].value_counts()

25.00     1361
26.00     1098
25.50     1015
25.25      954
25.20      948
          ...
320.50       1
315.50       1
220.01       1
321.40       1
132.48       1
Name: open, Length: 38992, dtype: int64

In [40]:
d.describe()

,open,high,low,close,adj_close,volume
count,1.476591e+06,1.476591e+06,1.476591e+06,1.476591e+06,1.476591e+06,1.476591e+06
mean,2.476045e+02,2.633086e+02,2.326614e+02,2.458154e+02,2.387080e+02,7.034831e+05
std,1.505086e+04,1.709550e+04,1.347410e+04,1.502149e+04,1.476369e+04,6.382178e+06
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.405000e+01,2.416000e+01,2.394000e+01,2.405000e+01,2.152000e+01,3.100000e+03
50%,3.150000e+01,3.165000e+01,3.133000e+01,3.149000e+01,2.920000e+01,1.870000e+04
75%,4.960000e+01,4.977000e+01,4.936000e+01,4.958000e+01,4.513000e+01,1.099000e+05
max,4.588800e+06,6.459520e+06,4.576000e+06,5.295360e+06,5.204029e+06,7.153001e+08

In [42]:
e = d.drop(columns= ["high", "low"])
e

        fund_symbol  price_date   open  close  adj_close   volume
0               AAA  2020-09-09  25.10  25.07      24.85  17300.0
1               AAA  2020-09-10  25.06  25.07      24.85  23500.0
2               AAA  2020-09-11  25.04  25.03      24.81  33400.0
3               AAA  2020-09-14  25.01  25.02      24.80  13100.0
4               AAA  2020-09-15  25.02  25.01      24.79  12100.0
...             ...         ...    ...    ...        ...      ...
1476587        GURU  2018-04-18  30.82  30.86      29.69   4700.0
1476588        GURU  2018-04-19  30.77  30.58      29.42   6900.0
1476589        GURU  2018-04-20  30.49  30.41      29.26   2200.0
1476590        GURU  2018-04-23  30.45  30.31      29.16   3800.0
1476591        GURU         201    NaN    NaN        NaN      NaN

[1476592 rows x 6 columns]

In [44]:
e= d.drop(columns=["fund_symbol"])
e

         price_date   open   high    low  close  adj_close   volume
0        2020-09-09  25.10  25.12  25.07  25.07      24.85  17300.0
1        2020-09-10  25.06  25.07  25.05  25.07      24.85  23500.0
2        2020-09-11  25.04  25.05  25.02  25.03      24.81  33400.0
3        2020-09-14  25.01  25.06  25.01  25.02      24.80  13100.0
4        2020-09-15  25.02  25.03  25.01  25.01      24.79  12100.0
...             ...    ...    ...    ...    ...        ...      ...
1476587  2018-04-18  30.82  30.92  30.73  30.86      29.69   4700.0
1476588  2018-04-19  30.77  30.77  30.52  30.58      29.42   6900.0
1476589  2018-04-20  30.49  30.55  30.40  30.41      29.26   2200.0
1476590  2018-04-23  30.45  30.48  30.29  30.31      29.16   3800.0
1476591         201    NaN    NaN    NaN    NaN        NaN      NaN

[1476592 rows x 7 columns]

In [29]:
d.iloc[10:20]

   fund_symbol  price_date   open   high    low  close  adj_close    volume
10         AAA  2020-09-23  24.99  25.00  24.99  24.99      24.77    4400.0
11         AAA  2020-09-24  24.99  24.99  24.98  24.98      24.76    7000.0
12         AAA  2020-09-25  24.99  25.00  24.97  24.98      24.76  115400.0
13         AAA  2020-09-28  24.96  24.97  24.95  24.95      24.74    6200.0
14         AAA  2020-09-29  24.94  24.95  24.93  24.94      24.73    8000.0
15         AAA  2020-09-30  24.96  24.97  24.96  24.96      24.74    5400.0
16         AAA  2020-10-01  24.93  24.93  24.92  24.92      24.71   24900.0
17         AAA  2020-10-02  24.91  24.92  24.91  24.92      24.71    3000.0
18         AAA  2020-10-05  24.91  24.94  24.91  24.92      24.71   28900.0
19         AAA  2020-10-06  24.89  24.91  24.89  24.91      24.70    3900.0

In [30]:
d.iloc[:,[1,2,5]]

         price_date   open  close
0        2020-09-09  25.10  25.07
1        2020-09-10  25.06  25.07
2        2020-09-11  25.04  25.03
3        2020-09-14  25.01  25.02
4        2020-09-15  25.02  25.01
...             ...    ...    ...
1476587  2018-04-18  30.82  30.86
1476588  2018-04-19  30.77  30.58
1476589  2018-04-20  30.49  30.41
1476590  2018-04-23  30.45  30.31
1476591         201    NaN    NaN

[1476592 rows x 3 columns]

In [11]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
d = pd.read_csv("/content/ETF prices.csv")
d

,fund_symbol,price_date,open,high,low,close,adj_close,volume
0,AAA,2020-09-09,25.10,25.12,25.07,25.07,24.85,17300.0
1,AAA,2020-09-10,25.06,25.07,25.05,25.07,24.85,23500.0
2,AAA,2020-09-11,25.04,25.05,25.02,25.03,24.81,33400.0
3,AAA,2020-09-14,25.01,25.06,25.01,25.02,24.80,13100.0
4,AAA,2020-09-15,25.02,25.03,25.01,25.01,24.79,12100.0
...,...,...,...,...,...,...,...,...
1476587,GURU,2018-04-18,30.82,30.92,30.73,30.86,29.69,4700.0
1476588,GURU,2018-04-19,30.77,30.77,30.52,30.58,29.42,6900.0
1476589,GURU,2018-04-20,30.49,30.55,30.40,30.41,29.26,2200.0
1476590,GURU,2018-04-23,30.45,30.48,30.29,30.31,29.16,3800.0
1476591,GURU,201,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
import pandas as pd

In [14]:
import numpy as np
precios = np.random.rand(10)
closed = np.random.randint(1, 100, 10)

In [15]:
closed

array([72, 85, 69, 14, 48, 87, 87, 45, 87, 93])

In [16]:
diccionario={"Precios" : precios, "Cierre":closed}
import pandas as pd
precio=pd.DataFrame(diccionario)
precio

    Precios  Cierre
0  0.679849      72
1  0.616676      85
2  0.733262      69
3  0.704646      14
4  0.161052      48
5  0.101223      87
6  0.860494      87
7  0.158813      45
8  0.610576      87
9  0.145947      93

In [ ]:
precio[precio["Cierre"]>20]

    Precios  Cierre
0  0.831448      64
1  0.798795      75
2  0.324321      74
4  0.944341      98
5  0.749796      69
6  0.871508      98
7  0.362962      93
8  0.717596      21
9  0.715217      30